version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
      
  node-app:
    build: .
    container_name: node-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
volumes:
  mongo-data:
